version: '3'
services:
  app:
    image: honvid/nginx
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/home/logs/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/home/app
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    image: honvid/php-fpm:dev
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./src:/home/app
    depends_on:
      - mysql
      - redis
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "26379:6379"
    networks:
      - backend

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge